### ISSUE TITLE
Base the connections on datapath and not MOLES URL

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-wps-assets#2]
## wps_links file

The `wps_links.yml` file will need:

```
- wps_process_id: flamingo/data_subsetter/SubsetCRUTimeSeries
  wps_process_form: https://ceda-wps-ui.ceda.ac.uk/processes/execute?wps=data_subsetter&process=SubsetCRUTimeSeries
  wps_process_description: http://ceda-wps1.ceda.ac.uk:9001/wps?service=WPS&version=1.0.0&request=describeprocess&identifier=SubsetCRUTimeSeries
  wps_name: flamingo
  wps_ceda_name: data_subsetter 
  wps_process_name: SubsetCRUTimeSeries
  wps_process_link_text: "Extract a subset from the CRU Time Series data (in NetCDF/CSV)"
  data_assets:
     /badc/cru/data/cru_ts/cru_ts_4.05/data
     /badc/cru/data/cru_ts/cru_ts_4.04/data
```

## WPS-specific YAML files

The WPS-specific metadata, will include things like:

```
...
  application_url: "https://services.ceda.ac.uk/cedasite/register/info"
  datasets: 
    - name: cru_ts.4.04
      long_name: Climatic Research Unit (CRU) TS (time-series) dataset 4.04
      time_range: "1901-01-16/2019-12-16"
      files: "/badc/cru/data/cru_ts/cru_ts_4.04/data/{var_id}/cru_ts4.04.1901.2019.{var}.dat.nc"
    - name: cru_ts.4.05
      long_name: Climatic Research Unit (CRU) TS (time-series) dataset 4.05
      time_range: "1901-01-16/2020-12-16"
      files: "/badc/cru/data/cru_ts/cru_ts_4.05/data/wet/cru_ts4.05.1901.2020.wet.dat.nc.gz"
      default: True
```

The WPS will use a cache (e.g. `@functools.lru_cache`) for looking up the relevant MOLES record(s) and providing a link to them in the WPS Metadata (which gets displayed on the form).

The datapath to the files will be split with:
`lookup_path = os.path.split(files_pattern.split("{")[0])[0]`

## Updating MOLES

The script to update MOLES will need to:
 1. Parse the `wps_links.yml` file
 2. Loop through each WPS process
 3. Identify the relevant data paths and detect MOLES records to add links for
 4. Add OnlineResource links using:
   - URL: `rec["wps_process_form"]`
   - Link text: `rec["wps_process_link_text"]`
